[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
serde = "1.0.210"
serde_json = "1.0.128"
sqlx = "0.8.2"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
tower = "0.5.1"
tower-http = { version = "0.5.2", features = ["normalize-path", "fs", "cors"] }

